{% set version = "2.0.9" %}

package:
  name: bob.io.audio
  version: {{ version }}

source:
  fn: bob.io.audio-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.io.audio/bob.io.audio-{{ version }}.zip
  md5: ab9ab5048daf1e0b24a2f7176c9c6de5

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - scipy
    - bob.extension >2.0.4
    - bob.blitz
    - bob.core
    - bob.io.base
    - bob.io.matlab
    - boost 1.62.*
    - sox 14.4.2
    - pkg-config

  run:
    - python
    - scipy
    - bob.extension >2.0.4
    - bob.blitz
    - bob.core
    - bob.io.base
    - bob.io.matlab
    - boost 1.62.*
    - sox 14.4.2

test:
  imports:
    - bob
    - bob.io
    - bob.io.audio

  commands:
    - nosetests -sv bob.io.audio

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: GNU General Public License v3 (GPLv3)
  summary: Audio I/O support for Bob

extra:
  recipe-maintainers:
    - 183amir
